'use strict';
/**
 * House style and claim checker.
 *
 * Enforces the rules agreed for this project against every template, stylesheet,
 * script and every string that reaches a page from the database:
 *
 *   no unsupported superlatives or guarantees
 *   no fabricated review, rating or counter markup
 *   no em dashes
 *   no emoji used as an icon
 *   no purple gradient, no gradient at all
 *   no fully rounded pill buttons
 *   no "made with AI" style badge
 *   no scroll driven animation, no custom cursor
 *
 * Usage: npm run audit:claims
 */
const fs = require('fs');
const path = require('path');
const Database = require('better-sqlite3');
const { findClaims } = require('../src/sanitize');

const ROOT = path.resolve(__dirname, '..');
const failures = [];
const notes = [];

function files(dir, exts) {
  const out = [];
  (function walk(d) {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      if (e.isDirectory()) {
        if (['node_modules', '.git', 'data'].includes(e.name)) continue;
        walk(path.join(d, e.name));
      } else if (exts.some((x) => e.name.endsWith(x))) {
        out.push(path.join(d, e.name));
      }
    }
  })(dir);
  return out;
}

const STYLE_RULES = [
  { id: 'em-dash', re: /\u2014/, message: 'em dash found, house style uses a plain sentence or a comma' },
  { id: 'emoji', re: /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/u, message: 'emoji found, icons must be inline SVG' },
  { id: 'gradient', re: /linear-gradient|radial-gradient|conic-gradient/i, message: 'CSS gradient found, the design uses flat colour only' },
  { id: 'purple', re: /#(6|7|8|9)[0-9a-f]{1}[0-9a-f]{2}f[0-9a-f]{2}\b|rebeccapurple|blueviolet|mediumpurple/i, message: 'purple-ish colour token found' },
  { id: 'pill-button', re: /\.btn[^{]*\{[^}]*border-radius:\s*(999|9999|50%|100px|2rem|3rem)/i, message: 'pill shaped button radius found' },
  { id: 'scroll-anim', re: /animation-timeline|scroll-timeline|data-aos|AOS\.init|ScrollTrigger/i, message: 'scroll driven animation library or property found' },
  { id: 'cursor-anim', re: /cursor-follow|custom-cursor|cursorDot|mousemove.*cursor/i, message: 'custom cursor effect found' },
  { id: 'ai-badge', re: /made with ai|built with ai|generated by ai|powered by chatgpt/i, message: 'AI attribution badge found' },
  { id: 'fake-review', re: /"aggregateRating"\s*:|"@type":\s*"Review"|itemprop="ratingValue"/i, message: 'rating or review markup found and there are no genuine reviews' },
  { id: 'counter', re: /countUp|odometer|data-counter|counter-animate/i, message: 'animated counter found' },
  { id: 'lorem', re: /lorem ipsum/i, message: 'placeholder lorem text left in a template' }
];

const EXEMPT = ['scripts/check-claims.js', 'scripts/check-seo.js', 'scripts/scan-secrets.js', 'src/sanitize.js'];
const rel_exempt = (f) => EXEMPT.some((e) => path.relative(ROOT, f) === e);

console.log('Checking templates, styles and scripts ...');
for (const file of files(ROOT, ['.ejs', '.css', '.js', '.json', '.md'])) {
  // The audit tooling itself contains the patterns it looks for, so it is exempt.
  if (rel_exempt(file)) continue;
  const rel = path.relative(ROOT, file);
  const text = fs.readFileSync(file, 'utf8');
  text.split('\n').forEach((line, i) => {
    for (const rule of STYLE_RULES) {
      if (rule.re.test(line)) failures.push(`${rel}:${i + 1}  [${rule.id}] ${rule.message}\n      ${line.trim().slice(0, 120)}`);
    }
  });

  if (file.endsWith('.ejs')) {
    // Claim screening only applies to prose the site publishes, not to code.
    const prose = text.replace(/<%[\s\S]*?%>/g, ' ').replace(/<[^>]+>/g, ' ');
    const claims = findClaims(prose);
    if (claims.length) failures.push(`${rel}  [claim] unsupported claim wording: ${claims.join(', ')}`);
  }
}

console.log('Checking button labels ...');
for (const file of files(path.join(ROOT, 'views'), ['.ejs'])) {
  const rel = path.relative(ROOT, file);
  const text = fs.readFileSync(file, 'utf8');
  const labels = [...text.matchAll(/<button[^>]*>([\s\S]*?)<\/button>/g)].map((m) => m[1].replace(/<%[\s\S]*?%>/g, '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim());
  for (const label of labels) {
    if (!label) { failures.push(`${rel}  [button] a button has no text label`); continue; }
    if (/^(submit|send|go|ok|click here|continue|next|yes|no)$/i.test(label)) {
      failures.push(`${rel}  [button] vague button label "${label}", say what the button does`);
    }
  }
}

console.log('Checking published catalogue strings ...');
const dbPath = path.join(ROOT, 'data', 'catalog.db');
if (fs.existsSync(dbPath)) {
  const db = new Database(dbPath, { readonly: true });
  const rows = db.prepare('SELECT id, slug, name, summary, client_copy FROM products').all();
  let claimCount = 0;
  for (const r of rows) {
    for (const field of ['name', 'summary', 'client_copy']) {
      const claims = findClaims(r[field]);
      if (claims.length) {
        claimCount++;
        notes.push(`product ${r.id} (${r.slug}) field ${field}: ${claims.join(', ')}`);
      }
    }
  }
  console.log(`  ${rows.length} products checked, ${claimCount} field(s) carrying claim wording`);
  db.close();
} else {
  notes.push('catalog.db not built yet, catalogue strings not checked');
}

/* --------------------------------------------------------- report */

console.log('');
if (notes.length) {
  console.log('Notes (review, not automatic failures):');
  for (const n of notes.slice(0, 40)) console.log('  ' + n);
  if (notes.length > 40) console.log(`  ... and ${notes.length - 40} more`);
  console.log('');
}
if (!failures.length) {
  console.log('House style and claim check passed.');
  process.exit(0);
}
for (const f of failures) console.error('FAIL  ' + f);
console.error(`\n${failures.length} problem(s).`);
process.exit(1);
